# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af376ce1f09aa844e8068b68470d7729ce67ad4ad88c2b810073fb2ef51fe32ac4ebdf355e75339b7d58701b8cc924d34cbf9b8ed01f350481dbb435122962ee

test:
  secret_key_base: 3d11b0c3e0709435a3aa8cdd83dbd1a80d021aa9244876dca2ad8edd7567611cf2553896a31c2cc193295ed481ad4f7ce220d432b67dbeca323ed68785a5810c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
